#!/bin/bash
# locale
_CANDIDATE_LOCALE_LANG=('en_US.utf8')
#_CANDIDATE_LOCALE_LANG=('zh_CN.UTF-8' 'zh_CN.utf8')
_CANDIDATE_LOCALE_LANGUAGE=('en_US.utf8')

_set_locale() {
	local ALL_LOCALE
	ALL_LOCALE=$(locale -a)
	_get_target_locale() {
		local arr_candidate=("$@")
		for lang in "${arr_candidate[@]}"; do
			if echo "$ALL_LOCALE" | grep -q "$lang"; then
				echo "$lang"
				return 0
			fi
		done
		return 1
	}

	local target_locale_lang
	target_locale_lang="$(_get_target_locale "${_CANDIDATE_LOCALE_LANG[@]}")"
	if [ -n "$target_locale_lang" ]; then
		export LANG=$target_locale_lang
	fi

	local target_locale_language
	target_locale_language="$(_get_target_locale "${_CANDIDATE_LOCALE_LANGUAGE[@]}")"
	if [ -n "$target_locale_language" ]; then
		export LANGUAGE=$target_locale_language
	fi

	# export LC_ALL=en_US.utf8
}

_set_locale
