#!/bin/bash

# open file of current edit line showing with mst-open
_mts_bind_open_current_line() {
    local line="$READLINE_LINE"

    # trim
    line="${line%"${line##*[![:space:]]}"}"
    line="${line#"${line%%[![:space:]]*}"}"

    if [[ -f "$line" || -d "$line" ]]; then
        mts-open "$line"
    else
        echo "file not exist $line" >&2
    fi
}

_mts_bind_res_get() {
    local selected
    selected="$(mts-res-get --print0 | xargs -0)"
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$((READLINE_POINT + ${#selected}))
}

_mts_bind_res_get_dir() {
    local selected
    selected="$(mts-res-get -d --print0 | xargs -0)"
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$((READLINE_POINT + ${#selected}))
}
_mts_bind_res_cd_dir() {
    local selected
    selected="$(mts-res-get -d --print0 | xargs -0)"
    [ -z "$selected" ] && {
        echo "no selected $selected"
        return 1
    }
    [ ! -d "$selected" ] && {
        echo "no a dir: $selected"
        return 1
    }
    cd "$selected" || {
        echo "cd $selected failed"
        return 1
    }
    echo "now on $(pwd)"
}

# open bin and insert output to current line
_mts_bind_bin_open_insert() {
    local selected
    selected="$(mts-bin-get)"
    local output
    output="$($selected)"
    READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$output${READLINE_LINE:$READLINE_POINT}"
    READLINE_POINT=$((READLINE_POINT + ${#output}))
}

bind -x '"\eaf":_mts_bind_open_current_line'
bind -x '"\earf":_mts_bind_res_get'
bind -x '"\ear\C-f":mts-res-open'
bind -x '"\eard":_mts_bind_res_get_dir'
bind '"\ear\C-d": "\C-ex\C-u _mts_bind_res_cd_dir\C-m\C-y\C-b\C-d"'
bind -x '"\eab ":mts-bin-exec'
bind -x '"\eabi":_mts_bind_bin_open_insert'
